/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author sabir ilyass
 */
public class fenetre extends javax.swing.JFrame {

    /**
     * Creates new form fenetre
     */

    String displayedNumber;
    boolean on = false; // This Boolean variable takes the value true if and only if the calculator is in use
    double value1, value2; 
    Operations operation;
    boolean operationOn = false;  // To check if you have clicked on an operation
    boolean scientific = false;
    boolean epi = false;

    public fenetre() {
        initComponents();
    }
    private void display(String number){
        if (lblAffichage.getText().equals("0") || operationOn){
           displayedNumber = number;
           operationOn = false;
        }
        else {
           displayedNumber = lblAffichage.getText()+number;
        }
        lblAffichage.setText(displayedNumber);
    }
    
    private boolean containDot(String number){
        return number.contains(".");
    }
    
    private void operation(Operations oper) {
        value1 = Double.parseDouble(lblAffichage.getText());
        operation = oper;
        operationOn = true;
    }
    
    private String deleteDot(String number){
        if (Double.parseDouble(number) == Math.floor(Double.parseDouble(number))){
           number = number.substring(0,number.length()-2);
        }
        return number;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblAffichage = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnModulo = new javax.swing.JButton();
        btnSquare = new javax.swing.JButton();
        btnSqrt = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btnSub = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btnMult = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btnDiv = new javax.swing.JButton();
        btnOp = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btnDot = new javax.swing.JButton();
        btnEqual = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        rbOn = new javax.swing.JRadioButton();
        rbOff = new javax.swing.JRadioButton();
        btnScientific = new javax.swing.JButton();
        btnUndo = new javax.swing.JButton();
        btnC = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnE = new javax.swing.JButton();
        btnPi = new javax.swing.JButton();
        btnExp = new javax.swing.JButton();
        btnLog = new javax.swing.JButton();
        btnPower = new javax.swing.JButton();
        btnCos = new javax.swing.JButton();
        btnTan = new javax.swing.JButton();
        btnSin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(400, 300));

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));
        jPanel1.setMinimumSize(new java.awt.Dimension(200, 200));

        lblAffichage.setBackground(new java.awt.Color(255, 255, 255));
        lblAffichage.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblAffichage.setForeground(new java.awt.Color(255, 0, 0));
        lblAffichage.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblAffichage.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAffichage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblAffichage, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.GridLayout(5, 4, 7, 7));

        btnModulo.setBackground(new java.awt.Color(255, 0, 0));
        btnModulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnModulo.setForeground(new java.awt.Color(255, 255, 255));
        btnModulo.setText("%");
        btnModulo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(202, 8, 9), 2));
        btnModulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModuloActionPerformed(evt);
            }
        });
        jPanel2.add(btnModulo);

        btnSquare.setBackground(new java.awt.Color(255, 0, 0));
        btnSquare.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSquare.setForeground(new java.awt.Color(255, 255, 255));
        btnSquare.setText("X²");
        btnSquare.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(202, 8, 9), 2));
        btnSquare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSquareActionPerformed(evt);
            }
        });
        jPanel2.add(btnSquare);

        btnSqrt.setBackground(new java.awt.Color(255, 0, 0));
        btnSqrt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSqrt.setForeground(new java.awt.Color(255, 255, 255));
        btnSqrt.setText("√X");
        btnSqrt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(202, 8, 9), 2));
        btnSqrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSqrtActionPerformed(evt);
            }
        });
        jPanel2.add(btnSqrt);

        btnAdd.setBackground(new java.awt.Color(255, 0, 0));
        btnAdd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("+");
        btnAdd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(202, 8, 9), 2));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel2.add(btnAdd);

        btn7.setBackground(new java.awt.Color(255, 0, 0));
        btn7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn7.setForeground(new java.awt.Color(255, 255, 255));
        btn7.setText("7");
        btn7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(202, 8, 9), 2));
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        jPanel2.add(btn7);

        btn8.setBackground(new java.awt.Color(255, 0, 0));
        btn8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn8.setForeground(new java.awt.Color(255, 255, 255));
        btn8.setText("8");
        btn8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(202, 8, 9), 2));
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        jPanel2.add(btn8);

        btn9.setBackground(new java.awt.Color(255, 0, 0));
        btn9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn9.setForeground(new java.awt.Color(255, 255, 255));
        btn9.setText("9");
        btn9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(202, 8, 9), 2));
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        jPanel2.add(btn9);

        btnSub.setBackground(new java.awt.Color(255, 0, 0));
        btnSub.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSub.setForeground(new java.awt.Color(255, 255, 255));
        btnSub.setText("-");
        btnSub.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(202, 8, 9), 2));
        btnSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubActionPerformed(evt);
            }
        });
        jPanel2.add(btnSub);

        btn4.setBackground(new java.awt.Color(255, 0, 0));
        btn4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn4.setForeground(new java.awt.Color(255, 255, 255));
        btn4.setText("4");
        btn4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(202, 8, 9), 2));
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        jPanel2.add(btn4);

        btn5.setBackground(new java.awt.Color(255, 0, 0));
        btn5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn5.setForeground(new java.awt.Color(255, 255, 255));
        btn5.setText("5");
        btn5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(202, 8, 9), 2));
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        jPanel2.add(btn5);

        btn6.setBackground(new java.awt.Color(255, 0, 0));
        btn6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn6.setForeground(new java.awt.Color(255, 255, 255));
        btn6.setText("6");
        btn6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(202, 8, 9), 2));
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        jPanel2.add(btn6);

        btnMult.setBackground(new java.awt.Color(255, 0, 0));
        btnMult.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnMult.setForeground(new java.awt.Color(255, 255, 255));
        btnMult.setText("×");
        btnMult.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(202, 8, 9), 2));
        btnMult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultActionPerformed(evt);
            }
        });
        jPanel2.add(btnMult);

        btn1.setBackground(new java.awt.Color(255, 0, 0));
        btn1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn1.setForeground(new java.awt.Color(255, 255, 255));
        btn1.setText("1");
        btn1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(202, 8, 9), 2));
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        jPanel2.add(btn1);

        btn2.setBackground(new java.awt.Color(255, 0, 0));
        btn2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn2.setForeground(new java.awt.Color(255, 255, 255));
        btn2.setText("2");
        btn2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(202, 8, 9), 2));
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        jPanel2.add(btn2);

        btn3.setBackground(new java.awt.Color(255, 0, 0));
        btn3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn3.setForeground(new java.awt.Color(255, 255, 255));
        btn3.setText("3");
        btn3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(202, 8, 9), 2));
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        jPanel2.add(btn3);

        btnDiv.setBackground(new java.awt.Color(255, 0, 0));
        btnDiv.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnDiv.setForeground(new java.awt.Color(255, 255, 255));
        btnDiv.setText("÷");
        btnDiv.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(202, 8, 9), 2));
        btnDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivActionPerformed(evt);
            }
        });
        jPanel2.add(btnDiv);

        btnOp.setBackground(new java.awt.Color(255, 0, 0));
        btnOp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnOp.setForeground(new java.awt.Color(255, 255, 255));
        btnOp.setText("+/-");
        btnOp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(202, 8, 9), 2));
        btnOp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpActionPerformed(evt);
            }
        });
        jPanel2.add(btnOp);

        btn0.setBackground(new java.awt.Color(255, 0, 0));
        btn0.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn0.setForeground(new java.awt.Color(255, 255, 255));
        btn0.setText("0");
        btn0.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(202, 8, 9), 2));
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });
        jPanel2.add(btn0);

        btnDot.setBackground(new java.awt.Color(255, 0, 0));
        btnDot.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnDot.setForeground(new java.awt.Color(255, 255, 255));
        btnDot.setText(".");
        btnDot.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(202, 8, 9), 2));
        btnDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDotActionPerformed(evt);
            }
        });
        jPanel2.add(btnDot);

        btnEqual.setBackground(new java.awt.Color(255, 0, 0));
        btnEqual.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnEqual.setForeground(new java.awt.Color(255, 255, 255));
        btnEqual.setText("=");
        btnEqual.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(202, 8, 9), 2));
        btnEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEqualActionPerformed(evt);
            }
        });
        jPanel2.add(btnEqual);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setToolTipText("");
        jPanel3.setMaximumSize(new java.awt.Dimension(300, 32767));
        jPanel3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPanel3KeyPressed(evt);
            }
        });
        jPanel3.setLayout(new java.awt.GridLayout(1, 5, 7, 7));

        rbOn.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rbOn);
        rbOn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rbOn.setText("On");
        rbOn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbOnActionPerformed(evt);
            }
        });
        jPanel3.add(rbOn);

        rbOff.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rbOff);
        rbOff.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rbOff.setSelected(true);
        rbOff.setText("Off");
        rbOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbOffActionPerformed(evt);
            }
        });
        jPanel3.add(rbOff);

        btnScientific.setBackground(new java.awt.Color(255, 0, 0));
        btnScientific.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnScientific.setForeground(new java.awt.Color(255, 255, 255));
        btnScientific.setText("Scien/Simple");
        btnScientific.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(202, 8, 9), 2));
        btnScientific.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnScientificActionPerformed(evt);
            }
        });
        jPanel3.add(btnScientific);

        btnUndo.setBackground(new java.awt.Color(255, 0, 0));
        btnUndo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnUndo.setForeground(new java.awt.Color(255, 255, 255));
        btnUndo.setText("DEL");
        btnUndo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(202, 8, 9), 2));
        btnUndo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUndoActionPerformed(evt);
            }
        });
        jPanel3.add(btnUndo);

        btnC.setBackground(new java.awt.Color(255, 0, 0));
        btnC.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnC.setForeground(new java.awt.Color(255, 255, 255));
        btnC.setText("Clear");
        btnC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(202, 8, 9), 2));
        btnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCActionPerformed(evt);
            }
        });
        jPanel3.add(btnC);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new java.awt.GridLayout(2, 4, 7, 7));

        btnE.setBackground(new java.awt.Color(255, 0, 0));
        btnE.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnE.setForeground(new java.awt.Color(255, 255, 255));
        btnE.setText("e");
        btnE.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(202, 8, 9), 2));
        btnE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEActionPerformed(evt);
            }
        });
        jPanel4.add(btnE);

        btnPi.setBackground(new java.awt.Color(255, 0, 0));
        btnPi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnPi.setForeground(new java.awt.Color(255, 255, 255));
        btnPi.setText("π");
        btnPi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(202, 8, 9), 2));
        btnPi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPiActionPerformed(evt);
            }
        });
        jPanel4.add(btnPi);

        btnExp.setBackground(new java.awt.Color(255, 0, 0));
        btnExp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnExp.setForeground(new java.awt.Color(255, 255, 255));
        btnExp.setText("exp");
        btnExp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(202, 8, 9), 2));
        btnExp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExpActionPerformed(evt);
            }
        });
        jPanel4.add(btnExp);

        btnLog.setBackground(new java.awt.Color(255, 0, 0));
        btnLog.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnLog.setForeground(new java.awt.Color(255, 255, 255));
        btnLog.setText("log");
        btnLog.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(202, 8, 9), 2));
        btnLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogActionPerformed(evt);
            }
        });
        jPanel4.add(btnLog);

        btnPower.setBackground(new java.awt.Color(255, 0, 0));
        btnPower.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnPower.setForeground(new java.awt.Color(255, 255, 255));
        btnPower.setText("X^Y");
        btnPower.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(202, 8, 9), 2));
        btnPower.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPowerActionPerformed(evt);
            }
        });
        jPanel4.add(btnPower);

        btnCos.setBackground(new java.awt.Color(255, 0, 0));
        btnCos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnCos.setForeground(new java.awt.Color(255, 255, 255));
        btnCos.setText("cos");
        btnCos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(202, 8, 9), 2));
        btnCos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCosActionPerformed(evt);
            }
        });
        jPanel4.add(btnCos);

        btnTan.setBackground(new java.awt.Color(255, 0, 0));
        btnTan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnTan.setForeground(new java.awt.Color(255, 255, 255));
        btnTan.setText("tan");
        btnTan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(202, 8, 9), 2));
        btnTan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTanActionPerformed(evt);
            }
        });
        jPanel4.add(btnTan);

        btnSin.setBackground(new java.awt.Color(255, 0, 0));
        btnSin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSin.setForeground(new java.awt.Color(255, 255, 255));
        btnSin.setText("sin");
        btnSin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(202, 8, 9), 2));
        btnSin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSinActionPerformed(evt);
            }
        });
        jPanel4.add(btnSin);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE))
        );

        jPanel3.getAccessibleContext().setAccessibleName("");
        jPanel3.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEqualActionPerformed
        // TODO add your handling code here:
        value2 = Double.parseDouble(lblAffichage.getText());
        if (null==operation)
            displayedNumber = String.valueOf("unrecognized operation");
        else switch (operation) {
            case add:
               displayedNumber = String.valueOf(value1 + value2);
               break;
            case sub:
               displayedNumber = String.valueOf(value1 - value2);
               break;
            case multiplication:
               displayedNumber = String.valueOf(value1 * value2);
               break;
            case division:
               displayedNumber = String.valueOf(value1 / value2);
               break;
            case modulo:
               displayedNumber = String.valueOf(value1 % value2);
               break;
            case power:
               displayedNumber = String.valueOf(Math.pow(value1,value2));
               break;
        }
        lblAffichage.setText(deleteDot(displayedNumber));
        epi = true;

    }//GEN-LAST:event_btnEqualActionPerformed

    private void rbOnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbOnActionPerformed
        // TODO add your handling code here:
        on = true;
        displayedNumber = "0";
        lblAffichage.setText(displayedNumber);
    }//GEN-LAST:event_rbOnActionPerformed

    private void rbOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbOffActionPerformed
        // TODO add your handling code here:
        on = false;
        displayedNumber = "";
        lblAffichage.setText(displayedNumber);
        epi = false;
    }//GEN-LAST:event_rbOffActionPerformed

    private void btnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCActionPerformed
        // TODO add your handling code here:
        if (on){
             displayedNumber = "0";
             lblAffichage.setText(displayedNumber);
             epi = false;
        }
    }//GEN-LAST:event_btnCActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        // TODO add your handling code here:
        if (on){
             displayedNumber = "0";
             lblAffichage.setText(displayedNumber);
        }
    }//GEN-LAST:event_btn0ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
        if (on) {
            display("1");
        }
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
        if (on) {
            display("7");
        }
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
        if (on) {
            display("3");
        }
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
        if (on) {
            display("4");
        }
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        // TODO add your handling code here:

        if (on) {
            display("5");
        }
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        // TODO add your handling code here:
        if (on) {
            display("6");
        }
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        // TODO add your handling code here:
        if (on) {
            display("7");
        }
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        // TODO add your handling code here:
        if (on) {
            display("8");
        }
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        // TODO add your handling code here:
        if (on) {
            display("9");
        }
    }//GEN-LAST:event_btn9ActionPerformed

    private void btnSquareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSquareActionPerformed
        // TODO add your handling code here:
        if (on){
           displayedNumber = lblAffichage.getText();
           Double number = Math.pow(Double.parseDouble(displayedNumber),2);
           displayedNumber=String.valueOf(number);
           lblAffichage.setText(displayedNumber);
        }
        
    }//GEN-LAST:event_btnSquareActionPerformed

    private void btnSqrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSqrtActionPerformed
        // TODO add your handling code here: 
        if (on){
           displayedNumber = lblAffichage.getText();
           Double number = Math.sqrt(Double.parseDouble(displayedNumber));
           displayedNumber=String.valueOf(number);
           lblAffichage.setText(displayedNumber);
        }
    }//GEN-LAST:event_btnSqrtActionPerformed

    private void btnModuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModuloActionPerformed
        // TODO add your handling code here:
        if (on) {
           operation(Operations.modulo);   
        } 
    }//GEN-LAST:event_btnModuloActionPerformed

    private void btnOpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpActionPerformed
        // TODO add your handling code here:
        if (on){
           displayedNumber = lblAffichage.getText();
           if (displayedNumber !=""){
                Double number = (-1)*(Double.parseDouble(displayedNumber));
                displayedNumber=String.valueOf(number);
                lblAffichage.setText(displayedNumber);
            }

        }
    }//GEN-LAST:event_btnOpActionPerformed

    private void btnEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEActionPerformed
        // TODO add your handling code here:
        if (on) {
            if (!epi){
               display(String.valueOf(Math.exp(1)));               
            }
        epi = true;
        }
    }//GEN-LAST:event_btnEActionPerformed

    private void btnPiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPiActionPerformed
        // TODO add your handling code here:
        if (on) {
            if (!epi){
               display(String.valueOf(Math.PI));             
            }
        epi = true;
        }
    }//GEN-LAST:event_btnPiActionPerformed

    private void btnExpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExpActionPerformed
        // TODO add your handling code here:
        if (on) {
            displayedNumber = lblAffichage.getText();
            double number = Math.exp(Double.parseDouble(displayedNumber));
            displayedNumber = String.valueOf(number);
            lblAffichage.setText(deleteDot(displayedNumber));
        }
    }//GEN-LAST:event_btnExpActionPerformed

    private void btnLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogActionPerformed
        // TODO add your handling code here:
        if (on) {
            displayedNumber = lblAffichage.getText();
            double number = Math.log(Double.parseDouble(displayedNumber));
            displayedNumber = String.valueOf(number);
            lblAffichage.setText(deleteDot(displayedNumber));

        }
    }//GEN-LAST:event_btnLogActionPerformed

    private void btnPowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPowerActionPerformed
        // TODO add your handling code here:
        if (on) {
           operation(Operations.power); 
           epi = false;  
        } 
    }//GEN-LAST:event_btnPowerActionPerformed

    private void btnCosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCosActionPerformed
        // TODO add your handling code here:
        if (on) {
           displayedNumber = lblAffichage.getText();
           double number = Math.cos(Double.parseDouble(displayedNumber));
           displayedNumber = String.valueOf(number); 
           lblAffichage.setText(deleteDot(displayedNumber));

        }
    }//GEN-LAST:event_btnCosActionPerformed

    private void btnTanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTanActionPerformed
        // TODO add your handling code here:
        if (on) {
           displayedNumber = lblAffichage.getText();
           double number = Math.tan(Double.parseDouble(displayedNumber));
           displayedNumber = String.valueOf(number); 
           lblAffichage.setText(deleteDot(displayedNumber));
        } 
    }//GEN-LAST:event_btnTanActionPerformed

    private void btnSinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSinActionPerformed
        // TODO add your handling code here:
       if (on) {
           displayedNumber = lblAffichage.getText();
           double number = Math.sin(Double.parseDouble(displayedNumber));
           displayedNumber = String.valueOf(number); 
           lblAffichage.setText(deleteDot(displayedNumber));
        } 
    }//GEN-LAST:event_btnSinActionPerformed

    private void btnUndoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUndoActionPerformed
        // TODO add your handling code here:
        if (on){
           displayedNumber = lblAffichage.getText();
           if (displayedNumber.length()>1)
               displayedNumber = displayedNumber.substring(0,displayedNumber.length()-1);
           else
               displayedNumber = "0";
               lblAffichage.setText(displayedNumber);
               epi = false;
        }
    }//GEN-LAST:event_btnUndoActionPerformed

    private void btnSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubActionPerformed
        // TODO add your handling code here:
        if (on) {
           operation(Operations.sub);  
           epi = false; 
        }
    }//GEN-LAST:event_btnSubActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
       if (on) {
           operation(Operations.add);
           epi = false;   
        } 
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnMultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultActionPerformed
        // TODO add your handling code here:
        if (on) {
           operation(Operations.multiplication);   
           epi = false;
        }
    }//GEN-LAST:event_btnMultActionPerformed

    private void btnDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivActionPerformed
        // TODO add your handling code here:
        if (on) {
           operation(Operations.division); 
           epi = false;  
        } 
    }//GEN-LAST:event_btnDivActionPerformed

    private void btnDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDotActionPerformed
        // TODO add your handling code here:
        if (on){
           displayedNumber = lblAffichage.getText();
           if ( !containDot(displayedNumber) && displayedNumber !="" ){
              displayedNumber = lblAffichage.getText() + ".";
           }
           lblAffichage.setText(displayedNumber);
        }
    }//GEN-LAST:event_btnDotActionPerformed

    private void btnScientificActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnScientificActionPerformed
        // TODO add your handling code here:
       if (on){
            if (!scientific){
                 jPanel4.setVisible(true);
            }
            else{
                 jPanel4.setVisible(false);
            }
            scientific = !scientific;
       }




    }//GEN-LAST:event_btnScientificActionPerformed

    private void jPanel3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel3KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel3KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fenetre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnC;
    private javax.swing.JButton btnCos;
    private javax.swing.JButton btnDiv;
    private javax.swing.JButton btnDot;
    private javax.swing.JButton btnE;
    private javax.swing.JButton btnEqual;
    private javax.swing.JButton btnExp;
    private javax.swing.JButton btnLog;
    private javax.swing.JButton btnModulo;
    private javax.swing.JButton btnMult;
    private javax.swing.JButton btnOp;
    private javax.swing.JButton btnPi;
    private javax.swing.JButton btnPower;
    private javax.swing.JButton btnScientific;
    private javax.swing.JButton btnSin;
    private javax.swing.JButton btnSqrt;
    private javax.swing.JButton btnSquare;
    private javax.swing.JButton btnSub;
    private javax.swing.JButton btnTan;
    private javax.swing.JButton btnUndo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblAffichage;
    private javax.swing.JRadioButton rbOff;
    private javax.swing.JRadioButton rbOn;
    // End of variables declaration//GEN-END:variables
}
